<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 5 HW4 | Data 624 - HA Assignments (HW1)</title>
  <meta name="description" content="Group 1’s HA Homework Assignments">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 5 HW4 | Data 624 - HA Assignments (HW1)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Group 1’s HA Homework Assignments" />
  <meta name="github-repo" content="baroncurtin2/data624" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 HW4 | Data 624 - HA Assignments (HW1)" />
  
  <meta name="twitter:description" content="Group 1’s HA Homework Assignments" />
  

<meta name="author" content="Group 1: Andrew Carson, Nathan Cooper, Baron Curtin, Heather Geiger">


<meta name="date" content="2019-03-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="hw3.html">
<link rel="next" href="hw5.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="hw1.html"><a href="hw1.html"><i class="fa fa-check"></i><b>2</b> HW1</a><ul>
<li class="chapter" data-level="2.1" data-path="hw1.html"><a href="hw1.html#section"><i class="fa fa-check"></i><b>2.1</b> 2.3</a><ul>
<li class="chapter" data-level="2.1.1" data-path="hw1.html"><a href="hw1.html#a"><i class="fa fa-check"></i><b>2.1.1</b> a</a></li>
<li class="chapter" data-level="2.1.2" data-path="hw1.html"><a href="hw1.html#b"><i class="fa fa-check"></i><b>2.1.2</b> b</a></li>
<li class="chapter" data-level="2.1.3" data-path="hw1.html"><a href="hw1.html#c"><i class="fa fa-check"></i><b>2.1.3</b> c</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="hw1.html"><a href="hw1.html#section-1"><i class="fa fa-check"></i><b>2.2</b> 2.7</a></li>
<li class="chapter" data-level="2.3" data-path="hw1.html"><a href="hw1.html#section-2"><i class="fa fa-check"></i><b>2.3</b> 2.10</a></li>
<li class="chapter" data-level="2.4" data-path="hw1.html"><a href="hw1.html#section-3"><i class="fa fa-check"></i><b>2.4</b> 3.1</a><ul>
<li class="chapter" data-level="2.4.1" data-path="hw1.html"><a href="hw1.html#usnetelec"><i class="fa fa-check"></i><b>2.4.1</b> usnetelec</a></li>
<li class="chapter" data-level="2.4.2" data-path="hw1.html"><a href="hw1.html#usgdp"><i class="fa fa-check"></i><b>2.4.2</b> usgdp</a></li>
<li class="chapter" data-level="2.4.3" data-path="hw1.html"><a href="hw1.html#mcopper"><i class="fa fa-check"></i><b>2.4.3</b> mcopper</a></li>
<li class="chapter" data-level="2.4.4" data-path="hw1.html"><a href="hw1.html#enplanements"><i class="fa fa-check"></i><b>2.4.4</b> enplanements</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hw1.html"><a href="hw1.html#section-4"><i class="fa fa-check"></i><b>2.5</b> 3.8</a><ul>
<li class="chapter" data-level="2.5.1" data-path="hw1.html"><a href="hw1.html#a-1"><i class="fa fa-check"></i><b>2.5.1</b> a</a></li>
<li class="chapter" data-level="2.5.2" data-path="hw1.html"><a href="hw1.html#b-1"><i class="fa fa-check"></i><b>2.5.2</b> b</a></li>
<li class="chapter" data-level="2.5.3" data-path="hw1.html"><a href="hw1.html#c-1"><i class="fa fa-check"></i><b>2.5.3</b> c</a></li>
<li class="chapter" data-level="2.5.4" data-path="hw1.html"><a href="hw1.html#d"><i class="fa fa-check"></i><b>2.5.4</b> d</a></li>
<li class="chapter" data-level="2.5.5" data-path="hw1.html"><a href="hw1.html#e"><i class="fa fa-check"></i><b>2.5.5</b> e</a></li>
<li class="chapter" data-level="2.5.6" data-path="hw1.html"><a href="hw1.html#f"><i class="fa fa-check"></i><b>2.5.6</b> f</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hw2.html"><a href="hw2.html"><i class="fa fa-check"></i><b>3</b> HW2</a><ul>
<li class="chapter" data-level="3.1" data-path="hw2.html"><a href="hw2.html#section-5"><i class="fa fa-check"></i><b>3.1</b> 6.2</a><ul>
<li class="chapter" data-level="3.1.1" data-path="hw2.html"><a href="hw2.html#a-2"><i class="fa fa-check"></i><b>3.1.1</b> a</a></li>
<li class="chapter" data-level="3.1.2" data-path="hw2.html"><a href="hw2.html#b-2"><i class="fa fa-check"></i><b>3.1.2</b> b</a></li>
<li class="chapter" data-level="3.1.3" data-path="hw2.html"><a href="hw2.html#c-2"><i class="fa fa-check"></i><b>3.1.3</b> c</a></li>
<li class="chapter" data-level="3.1.4" data-path="hw2.html"><a href="hw2.html#d-1"><i class="fa fa-check"></i><b>3.1.4</b> d</a></li>
<li class="chapter" data-level="3.1.5" data-path="hw2.html"><a href="hw2.html#e-1"><i class="fa fa-check"></i><b>3.1.5</b> e</a></li>
<li class="chapter" data-level="3.1.6" data-path="hw2.html"><a href="hw2.html#f-1"><i class="fa fa-check"></i><b>3.1.6</b> f</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hw2.html"><a href="hw2.html#section-6"><i class="fa fa-check"></i><b>3.2</b> 6.6</a><ul>
<li class="chapter" data-level="3.2.1" data-path="hw2.html"><a href="hw2.html#a-3"><i class="fa fa-check"></i><b>3.2.1</b> a</a></li>
<li class="chapter" data-level="3.2.2" data-path="hw2.html"><a href="hw2.html#b-3"><i class="fa fa-check"></i><b>3.2.2</b> b</a></li>
<li class="chapter" data-level="3.2.3" data-path="hw2.html"><a href="hw2.html#c-3"><i class="fa fa-check"></i><b>3.2.3</b> c</a></li>
<li class="chapter" data-level="3.2.4" data-path="hw2.html"><a href="hw2.html#d-2"><i class="fa fa-check"></i><b>3.2.4</b> d</a></li>
<li class="chapter" data-level="3.2.5" data-path="hw2.html"><a href="hw2.html#e-2"><i class="fa fa-check"></i><b>3.2.5</b> e</a></li>
<li class="chapter" data-level="3.2.6" data-path="hw2.html"><a href="hw2.html#f-2"><i class="fa fa-check"></i><b>3.2.6</b> f</a></li>
<li class="chapter" data-level="3.2.7" data-path="hw2.html"><a href="hw2.html#g"><i class="fa fa-check"></i><b>3.2.7</b> g</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hw3.html"><a href="hw3.html"><i class="fa fa-check"></i><b>4</b> HW3</a><ul>
<li class="chapter" data-level="4.1" data-path="hw3.html"><a href="hw3.html#section-7"><i class="fa fa-check"></i><b>4.1</b> 3.1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="hw3.html"><a href="hw3.html#a-4"><i class="fa fa-check"></i><b>4.1.1</b> 3.1a</a></li>
<li class="chapter" data-level="4.1.2" data-path="hw3.html"><a href="hw3.html#b-4"><i class="fa fa-check"></i><b>4.1.2</b> 3.1b</a></li>
<li class="chapter" data-level="4.1.3" data-path="hw3.html"><a href="hw3.html#c-4"><i class="fa fa-check"></i><b>4.1.3</b> 3.1c</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="hw3.html"><a href="hw3.html#section-8"><i class="fa fa-check"></i><b>4.2</b> 3.2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="hw3.html"><a href="hw3.html#a-5"><i class="fa fa-check"></i><b>4.2.1</b> 3.2a</a></li>
<li class="chapter" data-level="4.2.2" data-path="hw3.html"><a href="hw3.html#b-5"><i class="fa fa-check"></i><b>4.2.2</b> 3.2b</a></li>
<li class="chapter" data-level="4.2.3" data-path="hw3.html"><a href="hw3.html#c-5"><i class="fa fa-check"></i><b>4.2.3</b> 3.2c</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hw4.html"><a href="hw4.html"><i class="fa fa-check"></i><b>5</b> HW4</a><ul>
<li class="chapter" data-level="5.1" data-path="hw4.html"><a href="hw4.html#section-9"><i class="fa fa-check"></i><b>5.1</b> 7.5</a><ul>
<li class="chapter" data-level="5.1.1" data-path="hw4.html"><a href="hw4.html#a---exploratory-analysis"><i class="fa fa-check"></i><b>5.1.1</b> 7.5a - Exploratory analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="hw4.html"><a href="hw4.html#b---forecasting-with-ses"><i class="fa fa-check"></i><b>5.1.2</b> 7.5b - Forecasting with ses</a></li>
<li class="chapter" data-level="5.1.3" data-path="hw4.html"><a href="hw4.html#c---compute-rmse-values-for-the-training-data-in-each-case."><i class="fa fa-check"></i><b>5.1.3</b> 7.5c - Compute RMSE values for the training data in each case.</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="hw4.html"><a href="hw4.html#section-10"><i class="fa fa-check"></i><b>5.2</b> 7.6</a><ul>
<li class="chapter" data-level="5.2.1" data-path="hw4.html"><a href="hw4.html#a---apply-holts-linear-method-to-both-series-and-compute-four-day-forecasts-in-each-case."><i class="fa fa-check"></i><b>5.2.1</b> 7.6a - Apply Holt’s linear method to both series and compute four-day forecasts in each case.</a></li>
<li class="chapter" data-level="5.2.2" data-path="hw4.html"><a href="hw4.html#b---compare-rsme-measures-vs.-simple-exponential-smoothing."><i class="fa fa-check"></i><b>5.2.2</b> 7.6b - Compare RSME measures vs. simple exponential smoothing.</a></li>
<li class="chapter" data-level="5.2.3" data-path="hw4.html"><a href="hw4.html#c---compare-the-forecasts-for-the-two-series-using-both-methods.-which-do-you-think-is-best"><i class="fa fa-check"></i><b>5.2.3</b> 7.6c - Compare the forecasts for the two series using both methods. Which do you think is best?</a></li>
<li class="chapter" data-level="5.2.4" data-path="hw4.html"><a href="hw4.html#d---calculate-prediction-intervals-and-compare-to-intervals-from-ses-and-holt-functions."><i class="fa fa-check"></i><b>5.2.4</b> 7.6d - Calculate prediction intervals and compare to intervals from SES and Holt functions.</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="hw4.html"><a href="hw4.html#section-11"><i class="fa fa-check"></i><b>5.3</b> 7.10</a><ul>
<li class="chapter" data-level="5.3.1" data-path="hw4.html"><a href="hw4.html#a-6"><i class="fa fa-check"></i><b>5.3.1</b> 7.10a</a></li>
<li class="chapter" data-level="5.3.2" data-path="hw4.html"><a href="hw4.html#b-6"><i class="fa fa-check"></i><b>5.3.2</b> 7.10b</a></li>
<li class="chapter" data-level="5.3.3" data-path="hw4.html"><a href="hw4.html#c-6"><i class="fa fa-check"></i><b>5.3.3</b> 7.10c</a></li>
<li class="chapter" data-level="5.3.4" data-path="hw4.html"><a href="hw4.html#d-3"><i class="fa fa-check"></i><b>5.3.4</b> 7.10d</a></li>
<li class="chapter" data-level="5.3.5" data-path="hw4.html"><a href="hw4.html#e-3"><i class="fa fa-check"></i><b>5.3.5</b> 7.10e</a></li>
<li class="chapter" data-level="5.3.6" data-path="hw4.html"><a href="hw4.html#f-3"><i class="fa fa-check"></i><b>5.3.6</b> 7.10f</a></li>
<li class="chapter" data-level="5.3.7" data-path="hw4.html"><a href="hw4.html#g-1"><i class="fa fa-check"></i><b>5.3.7</b> 7.10g</a></li>
<li class="chapter" data-level="5.3.8" data-path="hw4.html"><a href="hw4.html#h"><i class="fa fa-check"></i><b>5.3.8</b> 7.10h</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hw5.html"><a href="hw5.html"><i class="fa fa-check"></i><b>6</b> HW5</a><ul>
<li class="chapter" data-level="6.0.1" data-path="hw5.html"><a href="hw5.html#section-12"><i class="fa fa-check"></i><b>6.0.1</b> 8.1</a></li>
<li class="chapter" data-level="6.0.2" data-path="hw5.html"><a href="hw5.html#section-13"><i class="fa fa-check"></i><b>6.0.2</b> 8.2</a></li>
<li class="chapter" data-level="6.0.3" data-path="hw5.html"><a href="hw5.html#section-14"><i class="fa fa-check"></i><b>6.0.3</b> 8.7</a></li>
<li class="chapter" data-level="6.0.4" data-path="hw5.html"><a href="hw5.html#section-15"><i class="fa fa-check"></i><b>6.0.4</b> 8.12</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data 624 - HA Assignments (HW1)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hw4" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> HW4</h1>
<div id="section-9" class="section level2">
<h2><span class="header-section-number">5.1</span> 7.5</h2>
<p><img src="week4/7.5.png" /></p>
<div id="a---exploratory-analysis" class="section level3">
<h3><span class="header-section-number">5.1.1</span> 7.5a - Exploratory analysis</h3>
<p>Start with a simple line plot.</p>
<pre class="sourceCode r"><code class="sourceCode r">books_dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Day =</span> <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>,<span class="dt">times=</span><span class="dv">2</span>),
    <span class="dt">Type =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Paperback&quot;</span>,<span class="st">&quot;Hardcover&quot;</span>),<span class="dt">each=</span><span class="dv">30</span>),
    <span class="dt">Sales =</span> <span class="kw">c</span>(books[,<span class="dv">1</span>],books[,<span class="dv">2</span>]),
    <span class="dt">stringsAsFactors=</span><span class="ot">FALSE</span>)
<span class="kw">ggplot</span>(books_dat,
<span class="kw">aes</span>(Day,Sales)) <span class="op">+</span>
<span class="kw">geom_line</span>() <span class="op">+</span>
<span class="kw">facet_wrap</span>(<span class="op">~</span>Type)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>It feels like there could potentially be a day of the week pattern here, but it’s a bit hard to tell from this plot.</p>
<p>Let’s plot each set of 7 days in its own panel.</p>
<pre class="sourceCode r"><code class="sourceCode r">books_dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(books_dat,
    <span class="dt">Day.of.week =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>,<span class="dt">times=</span><span class="dv">4</span>),<span class="dv">1</span>,<span class="dv">2</span>),<span class="dt">times=</span><span class="dv">2</span>),
    <span class="dt">Week =</span> <span class="kw">paste0</span>(<span class="st">&quot;Week&quot;</span>,<span class="kw">rep</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,<span class="dt">each=</span><span class="dv">7</span>),<span class="dv">5</span>,<span class="dv">5</span>),<span class="dt">times=</span><span class="dv">2</span>)),
    <span class="dt">stringsAsFactors=</span><span class="ot">FALSE</span>)
<span class="kw">ggplot</span>(books_dat,
<span class="kw">aes</span>(Day.of.week,Sales)) <span class="op">+</span>
<span class="kw">geom_line</span>() <span class="op">+</span>
<span class="kw">geom_point</span>() <span class="op">+</span>
<span class="kw">facet_grid</span>(Type <span class="op">~</span><span class="st"> </span>Week) <span class="op">+</span>
<span class="kw">xlab</span>(<span class="st">&quot;Day of the week&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>We don’t know here which actual day of the week from Sunday to Saturday each day of the week is, but we could infer if there were a weekday vs. weekend pattern if we saw two consecutive days consistently high/low.</p>
<p>Or if there were one particular day of the week with higher sales for whatever reason, we would be able to see it from this plot.</p>
<p>Here, it really does not seem like there is any pattern within what day of the week it is.</p>
<p>As for trend, it seems like there could possibly be an increasing trend, though it’s admittedly a bit hard to tell with such strong daily fluctuations. For our forecasting, we’ll move forward based on the assumption that there is no trend and just run simple exponential smoothing.</p>
</div>
<div id="b---forecasting-with-ses" class="section level3">
<h3><span class="header-section-number">5.1.2</span> 7.5b - Forecasting with ses</h3>
<p>Use the ses function to forecast.</p>
<pre class="sourceCode r"><code class="sourceCode r">paperback_forecast &lt;-<span class="st"> </span><span class="kw">ses</span>(books[,<span class="dv">1</span>],<span class="dt">h=</span><span class="dv">4</span>)
hardcover_forecast &lt;-<span class="st"> </span><span class="kw">ses</span>(books[,<span class="dv">2</span>],<span class="dt">h=</span><span class="dv">4</span>)
<span class="kw">autoplot</span>(paperback_forecast) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Day&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Sales&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="kw">ggtitle</span>(<span class="st">&quot;Paperback sales from past 30 days</span><span class="ch">\n</span><span class="st">+ forecast through next 4 days (with confidence intervals)&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(hardcover_forecast) <span class="op">+</span>
<span class="kw">xlab</span>(<span class="st">&quot;Day&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Sales&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="kw">ggtitle</span>(<span class="st">&quot;Hardcover sales from past 30 days</span><span class="ch">\n</span><span class="st">+ forecast through next 4 days (with confidence intervals)&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-59-2.png" width="672" /></p>
<p>Print the numbers for each.</p>
<pre><code>## [1] &quot;Paperback forecast:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">paperback_forecast</code></pre>
<pre><code>##    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 31       207.1097 162.4882 251.7311 138.8670 275.3523
## 32       207.1097 161.8589 252.3604 137.9046 276.3147
## 33       207.1097 161.2382 252.9811 136.9554 277.2639
## 34       207.1097 160.6259 253.5935 136.0188 278.2005</code></pre>
<pre><code>## [1] &quot;Hardcover forecast:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">hardcover_forecast</code></pre>
<pre><code>##    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 31       239.5601 197.2026 281.9176 174.7799 304.3403
## 32       239.5601 194.9788 284.1414 171.3788 307.7414
## 33       239.5601 192.8607 286.2595 168.1396 310.9806
## 34       239.5601 190.8347 288.2855 165.0410 314.0792</code></pre>
</div>
<div id="c---compute-rmse-values-for-the-training-data-in-each-case." class="section level3">
<h3><span class="header-section-number">5.1.3</span> 7.5c - Compute RMSE values for the training data in each case.</h3>
<p>The MSE (mean squared error) is already included in “mse” within the “model” from the forecast object.</p>
<p>Just take the square root of this to get the RSME (root mean squared error).</p>
<pre><code>## [1] &quot;RMSE paperback forecast:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(paperback_forecast<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 33.63769</code></pre>
<pre><code>## [1] &quot;RMSE hardcover forecast:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(hardcover_forecast<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 31.93101</code></pre>
<p>The RSME can be thought of as something similar to the standard deviation for the residuals. Basically, it’s a way to measure the spread of how much the actual values deviate from the predictions of the model within the training data.</p>
<p>Here, both paperback and hardcover forecasts have relatively similar RSME values of ~32-34. If the residuals are normally distributed, this means we would expect most predictions to fall within +/- 32-34 books vs. the actual value. While the vast majority would fall within +/- 64-68 books.</p>
</div>
</div>
<div id="section-10" class="section level2">
<h2><span class="header-section-number">5.2</span> 7.6</h2>
<p><img src="week4/7.6.png" /></p>
<div id="a---apply-holts-linear-method-to-both-series-and-compute-four-day-forecasts-in-each-case." class="section level3">
<h3><span class="header-section-number">5.2.1</span> 7.6a - Apply Holt’s linear method to both series and compute four-day forecasts in each case.</h3>
<pre class="sourceCode r"><code class="sourceCode r">paperback_holt &lt;-<span class="st"> </span><span class="kw">holt</span>(books[,<span class="dv">1</span>],<span class="dt">h=</span><span class="dv">4</span>)
hardcover_holt &lt;-<span class="st"> </span><span class="kw">holt</span>(books[,<span class="dv">2</span>],<span class="dt">h=</span><span class="dv">4</span>)
<span class="kw">autoplot</span>(paperback_holt) <span class="op">+</span>
<span class="kw">xlab</span>(<span class="st">&quot;Day&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Sales&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="kw">ggtitle</span>(<span class="st">&quot;Paperback sales from past 30 days</span><span class="ch">\n</span><span class="st">+ Holt&#39;s linear trend forecast through next 4 days&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(hardcover_holt) <span class="op">+</span>
<span class="kw">xlab</span>(<span class="st">&quot;Day&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&quot;Sales&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="kw">ggtitle</span>(<span class="st">&quot;Hardcover sales from past 30 days</span><span class="ch">\n</span><span class="st">+ Holt&#39;s linear trend forecast through next 4 days&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-68-2.png" width="672" /></p>
<pre><code>## [1] &quot;Paperback forecast using Holt&#39;s linear trend:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">paperback_holt</code></pre>
<pre><code>##    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 31       209.4668 166.6035 252.3301 143.9130 275.0205
## 32       210.7177 167.8544 253.5811 145.1640 276.2715
## 33       211.9687 169.1054 254.8320 146.4149 277.5225
## 34       213.2197 170.3564 256.0830 147.6659 278.7735</code></pre>
<pre><code>## [1] &quot;Hardcover forecast using Holt&#39;s linear trend:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">hardcover_holt</code></pre>
<pre><code>##    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 31       250.1739 212.7390 287.6087 192.9222 307.4256
## 32       253.4765 216.0416 290.9113 196.2248 310.7282
## 33       256.7791 219.3442 294.2140 199.5274 314.0308
## 34       260.0817 222.6468 297.5166 202.8300 317.3334</code></pre>
</div>
<div id="b---compare-rsme-measures-vs.-simple-exponential-smoothing." class="section level3">
<h3><span class="header-section-number">5.2.2</span> 7.6b - Compare RSME measures vs. simple exponential smoothing.</h3>
<p>First, calculate RSME for Holt’s forecasts.</p>
<pre><code>## [1] &quot;RSME for Holt&#39;s on paperback&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(paperback_holt<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 31.13692</code></pre>
<pre><code>## [1] &quot;RMSE for Holt&#39;s on hardcover&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(hardcover_holt<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 27.19358</code></pre>
<p>The RMSE error values using Holt’s linear trend is lower for both series than using simple exponential smoothing.</p>
<p>Assuming both methods have a mean of the residuals around 0, this would mean that we should prefer Holt’s linear trend, since its predictions show less deviation from being perfectly accurate.</p>
<p>However, this is a big assumption! Let’s check if it’s true.</p>
<pre><code>## [1] &quot;Means of residuals for SES, then Holt&#39;s, for paperback series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(paperback_forecast<span class="op">$</span>residuals)</code></pre>
<pre><code>## [1] 7.175981</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(paperback_holt<span class="op">$</span>residuals)</code></pre>
<pre><code>## [1] -3.717178</code></pre>
<pre><code>## [1] &quot;Means of residuals for SES, then Holt&#39;s, for hardcover series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(hardcover_forecast<span class="op">$</span>residuals)</code></pre>
<pre><code>## [1] 9.166735</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(hardcover_holt<span class="op">$</span>residuals)</code></pre>
<pre><code>## [1] -0.1357882</code></pre>
<p>Looks like the mean of the residuals using Holt’s is actually closer to 0 than for SES, so that’s another check in favor of Holt’s.</p>
<p>Finally, let’s visualize the distribution of residuals as well as plot time vs. residuals.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
hist_residuals &lt;-<span class="st"> </span><span class="cf">function</span>(residuals,title){
    <span class="kw">hist</span>(residuals,
        <span class="dt">xlab=</span><span class="st">&quot;Residuals&quot;</span>,
        <span class="dt">ylab=</span><span class="st">&quot;Number of predictions&quot;</span>,
        <span class="dt">labels=</span><span class="ot">TRUE</span>,
        <span class="dt">breaks=</span><span class="kw">seq</span>(<span class="dt">from=</span><span class="op">-</span><span class="dv">80</span>,<span class="dt">to=</span><span class="dv">80</span>,<span class="dt">by=</span><span class="dv">20</span>),
        <span class="dt">main=</span>title)
}
<span class="kw">hist_residuals</span>(paperback_forecast<span class="op">$</span>residuals,
    <span class="st">&quot;Paperback, SES&quot;</span>)
<span class="kw">hist_residuals</span>(paperback_holt<span class="op">$</span>residuals,
    <span class="st">&quot;Paperback, Holt&#39;s linear&quot;</span>)
<span class="kw">hist_residuals</span>(hardcover_forecast<span class="op">$</span>residuals,
    <span class="st">&quot;Hardcover, SES&quot;</span>)
<span class="kw">hist_residuals</span>(hardcover_holt<span class="op">$</span>residuals,
    <span class="st">&quot;Hardcover, Holt&#39;s linear&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-81-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">residuals_vs_time &lt;-<span class="st"> </span><span class="cf">function</span>(residuals,title){
    <span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>,
        residuals,
        <span class="dt">xlab=</span><span class="st">&quot;Day&quot;</span>,
        <span class="dt">ylab=</span><span class="st">&quot;Residuals&quot;</span>,
        <span class="dt">type=</span><span class="st">&quot;p&quot;</span>,
        <span class="dt">main=</span>title,
        <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">70</span>,<span class="dv">80</span>))
<span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>,<span class="dt">lty=</span><span class="dv">2</span>)
}
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">residuals_vs_time</span>(paperback_forecast<span class="op">$</span>residuals,
    <span class="st">&quot;Paperback, SES&quot;</span>)
<span class="kw">residuals_vs_time</span>(paperback_holt<span class="op">$</span>residuals,
    <span class="st">&quot;Paperback, Holt&#39;s linear&quot;</span>)
<span class="kw">residuals_vs_time</span>(hardcover_forecast<span class="op">$</span>residuals,
    <span class="st">&quot;Hardcover, SES&quot;</span>)
<span class="kw">residuals_vs_time</span>(hardcover_holt<span class="op">$</span>residuals,
    <span class="st">&quot;Hardcover, Holt&#39;s linear&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>The distributions of residuals look pretty similar. It’s hard to tell with only 30 data points, but they all seem relatively close to normal.</p>
<p>There does not seem to be any major bias across time for predictions to be in any one direction.</p>
<p>Therefore with these other factors being equal and RSME being lower using Holt’s linear trend, it seems that Holt’s linear trend has the clear advantage if we consider only performance within the training data.</p>
</div>
<div id="c---compare-the-forecasts-for-the-two-series-using-both-methods.-which-do-you-think-is-best" class="section level3">
<h3><span class="header-section-number">5.2.3</span> 7.6c - Compare the forecasts for the two series using both methods. Which do you think is best?</h3>
<p>We decided in part 2 that Holt’s linear trend would definitely be considered best if we looked only at performance within the training data.</p>
<p>Now, we are asked to also compare them using the forecasts into the future.</p>
<p>We saw above that SES gives the same forecast value for all four days into the future, with only the prediction intervals changing over time. Whereas Holt’s linear trend gives a different (in this case increasing) value for each point further out in time.</p>
<p>Paperback SES gave a prediction of 207.1097 books for all four days.</p>
<p>Meanwhile Holt’s method gave a prediction pretty close to the prediction from SES (209.4668 books) on the first day. But by the last day its prediction was decently higher (213.2197 books).</p>
<p>Similar idea for the hardcover series (239.5601 from SES, 250.1739 to 260.0817 from Holt’s linear method).</p>
<p>Let’s look at how many days had sales higher than these different predictions within each series.</p>
<pre><code>## [1] &quot;Days with sales higher than SES prediction, then first day Holt&#39;s prediction, then last day Holt&#39;s prediction, paperback series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span>paperback_forecast<span class="op">$</span>mean[<span class="dv">1</span>]))</code></pre>
<pre><code>## [1] 8</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span>paperback_holt<span class="op">$</span>mean[<span class="dv">1</span>]))</code></pre>
<pre><code>## [1] 7</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">1</span>] <span class="op">&gt;</span><span class="st"> </span>paperback_holt<span class="op">$</span>mean[<span class="dv">4</span>]))</code></pre>
<pre><code>## [1] 7</code></pre>
<pre><code>## [1] &quot;Same for hardcover series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">2</span>] <span class="op">&gt;</span><span class="st"> </span>hardcover_forecast<span class="op">$</span>mean[<span class="dv">1</span>]))</code></pre>
<pre><code>## [1] 5</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">2</span>] <span class="op">&gt;</span><span class="st"> </span>hardcover_holt<span class="op">$</span>mean[<span class="dv">1</span>]))</code></pre>
<pre><code>## [1] 3</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">which</span>(books[,<span class="dv">2</span>] <span class="op">&gt;</span><span class="st"> </span>hardcover_holt<span class="op">$</span>mean[<span class="dv">4</span>]))</code></pre>
<pre><code>## [1] 2</code></pre>
<p>We find that both SES and Holt’s method predict future sales that are higher than most sales of the past 30 days, for both series. So while the predictions using Holt’s method are even higher than for SES, it’s not like they are that much more out of the realm than the predictions from SES.</p>
<p>With this information combined with the better performance within the training data, I would continue to say that Holt’s linear trend is the better choice over SES for forecasting from this data.</p>
</div>
<div id="d---calculate-prediction-intervals-and-compare-to-intervals-from-ses-and-holt-functions." class="section level3">
<h3><span class="header-section-number">5.2.4</span> 7.6d - Calculate prediction intervals and compare to intervals from SES and Holt functions.</h3>
<p>First, let’s review the intervals from SES and Holt functions.</p>
<p>Prediction interval for first forecast from SES, paperback series: 138.8670-275.3523 (range ~136)</p>
<p>Holt’s linear trend, paperback series: 143.9130-275.0205 (range ~131)</p>
<p>SES, hardcover series: 174.7799-304.3403 (range ~130)</p>
<p>Holt’s linear trend, hardcover series: 192.9222-307.4256 (range ~115)</p>
<p>Now, compare to what we would get from calculating it ourselves using RMSE and assumption of a normal distribution.</p>
<pre class="sourceCode r"><code class="sourceCode r">zscore_for_95percent_interval &lt;-<span class="st"> </span><span class="kw">qnorm</span>(.<span class="dv">975</span>)</code></pre>
<pre><code>## [1] &quot;Intervals for SES then Holt&#39;s, paperback series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">plus_minus_interval &lt;-<span class="st"> </span><span class="kw">sqrt</span>(paperback_forecast<span class="op">$</span>model<span class="op">$</span>mse)<span class="op">*</span>zscore_for_95percent_interval
<span class="kw">c</span>(paperback_forecast<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>plus_minus_interval,paperback_forecast<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>plus_minus_interval)</code></pre>
<pre><code>## [1] 141.1810 273.0383</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">plus_minus_interval &lt;-<span class="st"> </span><span class="kw">sqrt</span>(paperback_holt<span class="op">$</span>model<span class="op">$</span>mse)<span class="op">*</span>zscore_for_95percent_interval
<span class="kw">c</span>(paperback_holt<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>plus_minus_interval,paperback_holt<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>plus_minus_interval)</code></pre>
<pre><code>## [1] 148.4395 270.4940</code></pre>
<pre><code>## [1] &quot;Intervals for SES then Holt&#39;s, hardcover series:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">plus_minus_interval &lt;-<span class="st"> </span><span class="kw">sqrt</span>(hardcover_forecast<span class="op">$</span>model<span class="op">$</span>mse)<span class="op">*</span>zscore_for_95percent_interval
<span class="kw">c</span>(hardcover_forecast<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>plus_minus_interval,hardcover_forecast<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>plus_minus_interval)</code></pre>
<pre><code>## [1] 176.9765 302.1437</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">plus_minus_interval &lt;-<span class="st"> </span><span class="kw">sqrt</span>(hardcover_holt<span class="op">$</span>model<span class="op">$</span>mse)<span class="op">*</span>zscore_for_95percent_interval
<span class="kw">c</span>(hardcover_holt<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>plus_minus_interval,hardcover_holt<span class="op">$</span>mean[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>plus_minus_interval)</code></pre>
<pre><code>## [1] 196.8754 303.4723</code></pre>
<p>To summarize again:</p>
<p>SES, paperback: 138.8670-275.3523 from function vs. 141.1810-273.0383 calculated</p>
<p>Holt’s, paperback: 143.9130-275.0205 vs. 148.4395-270.4940</p>
<p>SES, hardcover: 174.7799-304.3403 vs. 176.9765-302.1437</p>
<p>Holt’s, hardcover: 192.9222-307.4256 vs. 196.8754-303.4723</p>
<p>All of our calculated intervals are very slightly narrower than those given by the forecasting functions.</p>
<p>Overall though, they are quite similar.</p>
</div>
</div>
<div id="section-11" class="section level2">
<h2><span class="header-section-number">5.3</span> 7.10</h2>
<p><img src="week4/7.10.png" /></p>
<div id="a-6" class="section level3">
<h3><span class="header-section-number">5.3.1</span> 7.10a</h3>
<p><img src="week4/7.10a.png" /></p>
<p>Start with a simple line plot.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(ukcars) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;1977 to Q1 2005&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Also look at each quarter separately.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggsubseriesplot</span>(ukcars) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Yearly performance from 1977 to 2004/2005, separated by quarter&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>There is a clear seasonal component to the data, with lower sales on average in Q3.</p>
<p>There also appears to be an increasing trend, at least from around 1981-2000 or so.</p>
</div>
<div id="b-6" class="section level3">
<h3><span class="header-section-number">5.3.2</span> 7.10b</h3>
<p><img src="week4/7.10b.png" /></p>
<p>Let’s use the <strong>stl</strong> function to do this, and plot the result.</p>
<pre class="sourceCode r"><code class="sourceCode r">stl_decomp &lt;-<span class="st"> </span><span class="kw">stl</span>(ukcars,<span class="dt">s.window=</span><span class="st">&quot;periodic&quot;</span>)
<span class="kw">autoplot</span>(stl_decomp) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;STL decomposition of ukcars&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
<p>These results look pretty sensible. We can clearly see the dips in Q3 in the seasonal component, and the increasing trend throughout most of the time span in the trend component.</p>
</div>
<div id="c-6" class="section level3">
<h3><span class="header-section-number">5.3.3</span> 7.10c</h3>
<p><img src="week4/7.10c.png" /></p>
<p>As described in the question, use the function <strong>stlf()</strong> to do this.</p>
<p>Then, plot the seasonally adjusted data and corresponding forecast.</p>
<pre class="sourceCode r"><code class="sourceCode r">damped_forecast_after_stl &lt;-<span class="st"> </span>stl_decomp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">seasadj</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stlf</span>(<span class="dt">etsmodel=</span><span class="st">&quot;AAN&quot;</span>, <span class="dt">damped=</span><span class="ot">TRUE</span>,<span class="dt">h=</span><span class="dv">2</span>)
<span class="kw">autoplot</span>(damped_forecast_after_stl) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Time&quot;</span>) <span class="op">+</span>
<span class="kw">ylab</span>(<span class="st">&quot;Seasonally adjusted production&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-95-1.png" width="672" /></p>
</div>
<div id="d-3" class="section level3">
<h3><span class="header-section-number">5.3.4</span> 7.10d</h3>
<p><img src="week4/7.10d.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">non_damped_forecast_after_stl &lt;-<span class="st"> </span>stl_decomp <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">seasadj</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">    </span><span class="kw">stlf</span>(<span class="dt">etsmodel=</span><span class="st">&quot;AAN&quot;</span>, <span class="dt">damped=</span><span class="ot">FALSE</span>,<span class="dt">h=</span><span class="dv">2</span>)
<span class="kw">autoplot</span>(non_damped_forecast_after_stl) <span class="op">+</span><span class="st"> </span>
<span class="kw">xlab</span>(<span class="st">&quot;Time&quot;</span>) <span class="op">+</span>
<span class="kw">ylab</span>(<span class="st">&quot;Seasonally adjusted production&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
</div>
<div id="e-3" class="section level3">
<h3><span class="header-section-number">5.3.5</span> 7.10e</h3>
<p><img src="week4/7.10e.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">ets_model &lt;-<span class="st"> </span><span class="kw">ets</span>(ukcars)
ets_model<span class="op">$</span>components</code></pre>
<pre><code>## [1] &quot;A&quot;     &quot;N&quot;     &quot;A&quot;     &quot;FALSE&quot;</code></pre>
<p>The third letter denotes the season type. Here we get “A”, aka an additive seasonal model.</p>
</div>
<div id="f-3" class="section level3">
<h3><span class="header-section-number">5.3.6</span> 7.10f</h3>
<p><img src="week4/7.10f.png" /></p>
<pre><code>## [1] &quot;RSME damped trend after STL decomposition, non-damped after STL decomposition, and ETS automated model selection:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(damped_forecast_after_stl<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 23.32113</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(non_damped_forecast_after_stl<span class="op">$</span>model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 23.295</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(ets_model<span class="op">$</span>mse)</code></pre>
<pre><code>## [1] 25.23244</code></pre>
<p>Based on RSME, both models after STL decomposition perform better on the training data than the one using non-adjusted data and the ETS function.</p>
<p>The non-damped performs slightly better than the damped, but they are really extremely close.</p>
</div>
<div id="g-1" class="section level3">
<h3><span class="header-section-number">5.3.7</span> 7.10g</h3>
<p><img src="week4/7.10g.png" /></p>
<pre><code>## [1] &quot;Forecasts damped trend after STL decomposition, non-damped after STL decomposition, and ETS automated model selection:&quot;</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">damped_forecast_after_stl</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2005 Q2       394.0146 363.4433 424.5858 347.2599 440.7692
## 2005 Q3       409.3791 371.9947 446.7634 352.2047 466.5535</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">non_damped_forecast_after_stl</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2005 Q2       395.1772 364.7806 425.5738 348.6897 441.6648
## 2005 Q3       411.4591 373.9155 449.0027 354.0411 468.8771</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">ets_forecast &lt;-<span class="st"> </span><span class="kw">forecast</span>(ets_model,<span class="dt">h=</span><span class="dv">2</span>)
ets_forecast</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2005 Q2       427.4885 394.2576 460.7195 376.6662 478.3109
## 2005 Q3       361.3329 322.2353 400.4305 301.5383 421.1275</code></pre>
<p>The damped forecast has slightly lower forecast point values than the non-damped, as we would expect.</p>
<p>The ETS model predicts much higher Q2 production and much lower Q3 production than the other two models. However, it is hard to compare directly because the ETS model is based on non-adjusted data, while the others are based on adjusted data.</p>
<p>To convert the forecasts after STL decomposition to real-world realistic numbers, we would have to add back in the seasonal component to these forecasts.</p>
</div>
<div id="h" class="section level3">
<h3><span class="header-section-number">5.3.8</span> 7.10h</h3>
<p><img src="week4/7.10h.png" /></p>
<p>Let’s make a histogram and plot time vs. residuals for the ETS model.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
<span class="kw">hist</span>(ets_model<span class="op">$</span>residuals,
<span class="dt">labels=</span><span class="ot">TRUE</span>,
<span class="dt">xlab=</span><span class="st">&quot;Residuals&quot;</span>,
<span class="dt">ylab=</span><span class="st">&quot;Number of quarters&quot;</span>,
<span class="dt">main=</span><span class="st">&quot;ETS model&quot;</span>)
mycol &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;#E69F00&quot;</span>, <span class="st">&quot;#56B4E9&quot;</span>, <span class="st">&quot;#009E73&quot;</span>, <span class="st">&quot;#F0E442&quot;</span>, <span class="st">&quot;#0072B2&quot;</span>, <span class="st">&quot;#D55E00&quot;</span>, <span class="st">&quot;#CC79A7&quot;</span>,<span class="st">&quot;#490092&quot;</span>)
<span class="kw">plot</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1977</span><span class="op">:</span><span class="dv">2004</span>,<span class="dt">each=</span><span class="dv">4</span>),<span class="dv">2005</span>),
ets_model<span class="op">$</span>residuals,
<span class="dt">xlab=</span><span class="st">&quot;Time&quot;</span>,
<span class="dt">ylab=</span><span class="st">&quot;Residuals&quot;</span>,
<span class="dt">main=</span><span class="st">&quot;ETS model&quot;</span>,
<span class="dt">col=</span><span class="kw">c</span>(<span class="kw">rep</span>(mycol[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>],<span class="dt">times=</span><span class="kw">length</span>(<span class="dv">1977</span><span class="op">:</span><span class="dv">2004</span>)),mycol[<span class="dv">1</span>]))
<span class="kw">abline</span>(<span class="dt">h=</span><span class="dv">0</span>,<span class="dt">lty=</span><span class="dv">2</span>)
<span class="kw">legend</span>(<span class="st">&quot;bottom&quot;</span>,
<span class="dt">legend=</span><span class="kw">paste0</span>(<span class="st">&quot;Q&quot;</span>,<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>),
<span class="dt">col=</span>mycol,
<span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">bty=</span><span class="st">&quot;n&quot;</span>)</code></pre>
<p><img src="Data_624-Group_1-HW1_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>Residuals appear to be normally distributed and unbiased over time and season.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hw3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="hw5.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-Week4-HW.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Data 624-Group 1-HW1.pdf", "Data 624-Group 1-HW1.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
