<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 6 HW5 | Data 624 - HA Assignments (HW1)</title>
  <meta name="description" content="Group 1’s HA Homework Assignments">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 6 HW5 | Data 624 - HA Assignments (HW1)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Group 1’s HA Homework Assignments" />
  <meta name="github-repo" content="baroncurtin2/data624" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 HW5 | Data 624 - HA Assignments (HW1)" />
  
  <meta name="twitter:description" content="Group 1’s HA Homework Assignments" />
  

<meta name="author" content="Group 1: Andrew Carson, Nathan Cooper, Baron Curtin, Heather Geiger">


<meta name="date" content="2019-03-16">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="hw4.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data 624-Group1-HW1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="hw1.html"><a href="hw1.html"><i class="fa fa-check"></i><b>2</b> HW1</a><ul>
<li class="chapter" data-level="2.1" data-path="hw1.html"><a href="hw1.html#section"><i class="fa fa-check"></i><b>2.1</b> 2.3</a><ul>
<li class="chapter" data-level="2.1.1" data-path="hw1.html"><a href="hw1.html#a"><i class="fa fa-check"></i><b>2.1.1</b> a</a></li>
<li class="chapter" data-level="2.1.2" data-path="hw1.html"><a href="hw1.html#b"><i class="fa fa-check"></i><b>2.1.2</b> b</a></li>
<li class="chapter" data-level="2.1.3" data-path="hw1.html"><a href="hw1.html#c"><i class="fa fa-check"></i><b>2.1.3</b> c</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="hw1.html"><a href="hw1.html#section-1"><i class="fa fa-check"></i><b>2.2</b> 2.7</a></li>
<li class="chapter" data-level="2.3" data-path="hw1.html"><a href="hw1.html#section-2"><i class="fa fa-check"></i><b>2.3</b> 2.10</a></li>
<li class="chapter" data-level="2.4" data-path="hw1.html"><a href="hw1.html#section-3"><i class="fa fa-check"></i><b>2.4</b> 3.1</a><ul>
<li class="chapter" data-level="2.4.1" data-path="hw1.html"><a href="hw1.html#usnetelec"><i class="fa fa-check"></i><b>2.4.1</b> usnetelec</a></li>
<li class="chapter" data-level="2.4.2" data-path="hw1.html"><a href="hw1.html#usgdp"><i class="fa fa-check"></i><b>2.4.2</b> usgdp</a></li>
<li class="chapter" data-level="2.4.3" data-path="hw1.html"><a href="hw1.html#mcopper"><i class="fa fa-check"></i><b>2.4.3</b> mcopper</a></li>
<li class="chapter" data-level="2.4.4" data-path="hw1.html"><a href="hw1.html#enplanements"><i class="fa fa-check"></i><b>2.4.4</b> enplanements</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="hw1.html"><a href="hw1.html#section-4"><i class="fa fa-check"></i><b>2.5</b> 3.8</a><ul>
<li class="chapter" data-level="2.5.1" data-path="hw1.html"><a href="hw1.html#a-1"><i class="fa fa-check"></i><b>2.5.1</b> a</a></li>
<li class="chapter" data-level="2.5.2" data-path="hw1.html"><a href="hw1.html#b-1"><i class="fa fa-check"></i><b>2.5.2</b> b</a></li>
<li class="chapter" data-level="2.5.3" data-path="hw1.html"><a href="hw1.html#c-1"><i class="fa fa-check"></i><b>2.5.3</b> c</a></li>
<li class="chapter" data-level="2.5.4" data-path="hw1.html"><a href="hw1.html#d"><i class="fa fa-check"></i><b>2.5.4</b> d</a></li>
<li class="chapter" data-level="2.5.5" data-path="hw1.html"><a href="hw1.html#e"><i class="fa fa-check"></i><b>2.5.5</b> e</a></li>
<li class="chapter" data-level="2.5.6" data-path="hw1.html"><a href="hw1.html#f"><i class="fa fa-check"></i><b>2.5.6</b> f</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="hw2.html"><a href="hw2.html"><i class="fa fa-check"></i><b>3</b> HW2</a><ul>
<li class="chapter" data-level="3.1" data-path="hw2.html"><a href="hw2.html#section-5"><i class="fa fa-check"></i><b>3.1</b> 6.2</a><ul>
<li class="chapter" data-level="3.1.1" data-path="hw2.html"><a href="hw2.html#a-2"><i class="fa fa-check"></i><b>3.1.1</b> a</a></li>
<li class="chapter" data-level="3.1.2" data-path="hw2.html"><a href="hw2.html#b-2"><i class="fa fa-check"></i><b>3.1.2</b> b</a></li>
<li class="chapter" data-level="3.1.3" data-path="hw2.html"><a href="hw2.html#c-2"><i class="fa fa-check"></i><b>3.1.3</b> c</a></li>
<li class="chapter" data-level="3.1.4" data-path="hw2.html"><a href="hw2.html#d-1"><i class="fa fa-check"></i><b>3.1.4</b> d</a></li>
<li class="chapter" data-level="3.1.5" data-path="hw2.html"><a href="hw2.html#e-1"><i class="fa fa-check"></i><b>3.1.5</b> e</a></li>
<li class="chapter" data-level="3.1.6" data-path="hw2.html"><a href="hw2.html#f-1"><i class="fa fa-check"></i><b>3.1.6</b> f</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="hw2.html"><a href="hw2.html#section-6"><i class="fa fa-check"></i><b>3.2</b> 6.6</a><ul>
<li class="chapter" data-level="3.2.1" data-path="hw2.html"><a href="hw2.html#a-3"><i class="fa fa-check"></i><b>3.2.1</b> a</a></li>
<li class="chapter" data-level="3.2.2" data-path="hw2.html"><a href="hw2.html#b-3"><i class="fa fa-check"></i><b>3.2.2</b> b</a></li>
<li class="chapter" data-level="3.2.3" data-path="hw2.html"><a href="hw2.html#c-3"><i class="fa fa-check"></i><b>3.2.3</b> c</a></li>
<li class="chapter" data-level="3.2.4" data-path="hw2.html"><a href="hw2.html#d-2"><i class="fa fa-check"></i><b>3.2.4</b> d</a></li>
<li class="chapter" data-level="3.2.5" data-path="hw2.html"><a href="hw2.html#e-2"><i class="fa fa-check"></i><b>3.2.5</b> e</a></li>
<li class="chapter" data-level="3.2.6" data-path="hw2.html"><a href="hw2.html#f-2"><i class="fa fa-check"></i><b>3.2.6</b> f</a></li>
<li class="chapter" data-level="3.2.7" data-path="hw2.html"><a href="hw2.html#g"><i class="fa fa-check"></i><b>3.2.7</b> g</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="hw3.html"><a href="hw3.html"><i class="fa fa-check"></i><b>4</b> HW3</a><ul>
<li class="chapter" data-level="4.1" data-path="hw3.html"><a href="hw3.html#section-7"><i class="fa fa-check"></i><b>4.1</b> 3.1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="hw3.html"><a href="hw3.html#a-4"><i class="fa fa-check"></i><b>4.1.1</b> 3.1a</a></li>
<li class="chapter" data-level="4.1.2" data-path="hw3.html"><a href="hw3.html#b-4"><i class="fa fa-check"></i><b>4.1.2</b> 3.1b</a></li>
<li class="chapter" data-level="4.1.3" data-path="hw3.html"><a href="hw3.html#c-4"><i class="fa fa-check"></i><b>4.1.3</b> 3.1c</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="hw3.html"><a href="hw3.html#section-8"><i class="fa fa-check"></i><b>4.2</b> 3.2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="hw3.html"><a href="hw3.html#a-5"><i class="fa fa-check"></i><b>4.2.1</b> 3.2a</a></li>
<li class="chapter" data-level="4.2.2" data-path="hw3.html"><a href="hw3.html#b-5"><i class="fa fa-check"></i><b>4.2.2</b> 3.2b</a></li>
<li class="chapter" data-level="4.2.3" data-path="hw3.html"><a href="hw3.html#c-5"><i class="fa fa-check"></i><b>4.2.3</b> 3.2c</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hw4.html"><a href="hw4.html"><i class="fa fa-check"></i><b>5</b> HW4</a><ul>
<li class="chapter" data-level="5.1" data-path="hw4.html"><a href="hw4.html#section-9"><i class="fa fa-check"></i><b>5.1</b> 7.5</a><ul>
<li class="chapter" data-level="5.1.1" data-path="hw4.html"><a href="hw4.html#a-6"><i class="fa fa-check"></i><b>5.1.1</b> 7.5a</a></li>
<li class="chapter" data-level="5.1.2" data-path="hw4.html"><a href="hw4.html#b-6"><i class="fa fa-check"></i><b>5.1.2</b> 7.5b</a></li>
<li class="chapter" data-level="5.1.3" data-path="hw4.html"><a href="hw4.html#c-6"><i class="fa fa-check"></i><b>5.1.3</b> 7.5c</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="hw4.html"><a href="hw4.html#section-10"><i class="fa fa-check"></i><b>5.2</b> 7.6</a><ul>
<li class="chapter" data-level="5.2.1" data-path="hw4.html"><a href="hw4.html#a-7"><i class="fa fa-check"></i><b>5.2.1</b> 7.6a</a></li>
<li class="chapter" data-level="5.2.2" data-path="hw4.html"><a href="hw4.html#b-7"><i class="fa fa-check"></i><b>5.2.2</b> 7.6b</a></li>
<li class="chapter" data-level="5.2.3" data-path="hw4.html"><a href="hw4.html#c-7"><i class="fa fa-check"></i><b>5.2.3</b> 7.6c</a></li>
<li class="chapter" data-level="5.2.4" data-path="hw4.html"><a href="hw4.html#d-3"><i class="fa fa-check"></i><b>5.2.4</b> 7.6d</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="hw4.html"><a href="hw4.html#section-11"><i class="fa fa-check"></i><b>5.3</b> 7.10</a><ul>
<li class="chapter" data-level="5.3.1" data-path="hw4.html"><a href="hw4.html#a-8"><i class="fa fa-check"></i><b>5.3.1</b> 7.10a</a></li>
<li class="chapter" data-level="5.3.2" data-path="hw4.html"><a href="hw4.html#b-8"><i class="fa fa-check"></i><b>5.3.2</b> 7.10b</a></li>
<li class="chapter" data-level="5.3.3" data-path="hw4.html"><a href="hw4.html#c-8"><i class="fa fa-check"></i><b>5.3.3</b> 7.10c</a></li>
<li class="chapter" data-level="5.3.4" data-path="hw4.html"><a href="hw4.html#d-4"><i class="fa fa-check"></i><b>5.3.4</b> 7.10d</a></li>
<li class="chapter" data-level="5.3.5" data-path="hw4.html"><a href="hw4.html#e-3"><i class="fa fa-check"></i><b>5.3.5</b> 7.10e</a></li>
<li class="chapter" data-level="5.3.6" data-path="hw4.html"><a href="hw4.html#f-3"><i class="fa fa-check"></i><b>5.3.6</b> 7.10f</a></li>
<li class="chapter" data-level="5.3.7" data-path="hw4.html"><a href="hw4.html#g-1"><i class="fa fa-check"></i><b>5.3.7</b> 7.10g</a></li>
<li class="chapter" data-level="5.3.8" data-path="hw4.html"><a href="hw4.html#h"><i class="fa fa-check"></i><b>5.3.8</b> 7.10h</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hw5.html"><a href="hw5.html"><i class="fa fa-check"></i><b>6</b> HW5</a><ul>
<li class="chapter" data-level="6.0.1" data-path="hw5.html"><a href="hw5.html#section-12"><i class="fa fa-check"></i><b>6.0.1</b> 8.1</a></li>
<li class="chapter" data-level="6.0.2" data-path="hw5.html"><a href="hw5.html#section-13"><i class="fa fa-check"></i><b>6.0.2</b> 8.2</a></li>
<li class="chapter" data-level="6.0.3" data-path="hw5.html"><a href="hw5.html#section-14"><i class="fa fa-check"></i><b>6.0.3</b> 8.7</a></li>
<li class="chapter" data-level="6.0.4" data-path="hw5.html"><a href="hw5.html#section-15"><i class="fa fa-check"></i><b>6.0.4</b> 8.12</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data 624 - HA Assignments (HW1)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hw5" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> HW5</h1>
<div id="section-12" class="section level3">
<h3><span class="header-section-number">6.0.1</span> 8.1</h3>
<p><img src="week5/8.png" /></p>
<div id="a-9" class="section level4">
<h4><span class="header-section-number">6.0.1.1</span> 8.1a</h4>
<p><img src="week5/8.1a.png" /></p>
<p>Answer: An ACF plot shows the correlations from linear relationships between lagged values of a time series for various lags. The first plot has the largest magnitude of correlations amongst lagged values, with some getting to about 0.25 and -0.3. It also has the largest critical values (the blue lines). As we move to the right, the critical values decrease and the correlations also decrease in magnitude until in the third chart, one can hardly see the correlations.</p>
<p>I think that the charts pretty well show that the data are white noise. We don’t see any correlations far over the critical value lines so that suggests there aren’t correlations from one value to the next (meaning that it is in reasonable to assume that it is white noise).</p>
</div>
<div id="b-9" class="section level4">
<h4><span class="header-section-number">6.0.1.2</span> 8.1b</h4>
<p><img src="week5/8.1b.png" /></p>
<p>Answer: In the first chart, the sample size is so small (36), and the chances of an accidental correlation from that small sample are so great, that the correlation would have to be very high in order to be significant. This is why the critical values are pretty large in magnitude (around 0.3 and -0.3). As the number of values in each sample increases and we move to the right, the likelihood of getting an accidental correlation due purely to random luck decreases, so the critical values showing the bar for significance also decrease as even a very modest correlation is likely to be significant and not due purely to random luck.</p>
<p>Furthermore, the autocorrelations also decrease in magnitude as we move from left to right, as there are more and more examples of the relationship between one value and the next. When there are few values, it is very easy to find a correlation between subsequent values based solely on random luck coming from white noise. However, as more values are added, it becomes more difficult to find a correlation that is due to luck. Not finding a strong relationship, the correlation values decrease.</p>
</div>
</div>
<div id="section-13" class="section level3">
<h3><span class="header-section-number">6.0.2</span> 8.2</h3>
<p><img src="week5/8.2.png" /></p>
<p>Answer: We plot the data below. Just by looking at it we can tell that there are instances of trend and of decreasing variance. Consequently, we know that it is not stationary.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(fpp2)
<span class="kw">autoplot</span>(ibmclose)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>If we look at the ACF, we can see that each value is related to previous values. At each increasing lag value, there is still great signficance in the relationship between a value and the related lag value. This means that the time at which a value occurs is important to determining its value, so again, it is non-stationary.</p>
<p>In terms of difference, every lag value is significant. What we don’t know if whether the significance of lag 2, for example, comes from its relationshop to lag 1, or if is is significant on its own. Thats why we need to look at the PACF.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#ACF</span>
<span class="kw">acf</span>(ibmclose)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>The PACF removes the significance due to previous lags. This chart clearly shows that the lag of 1 is the significant lag, and any subsequent lags are significant only because they had the relationship with the first lag. So a difference of 1 is the correct difference to be applied here.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#PACF</span>
<span class="kw">pacf</span>(ibmclose)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
</div>
<div id="section-14" class="section level3">
<h3><span class="header-section-number">6.0.3</span> 8.7</h3>
<p><img src="week5/8.7.png" /></p>
<div id="a-10" class="section level4">
<h4><span class="header-section-number">6.0.3.1</span> 8.7a</h4>
<p><img src="week5/8.7a.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">autoplot</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>() <span class="op">%&gt;%</span><span class="kw">autoplot</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis-2.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>(<span class="dt">differences =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="kw">autoplot</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis-3.png" width="672" /></p>
<p>It looks like a random walk, though neither the difference nor the second order difference look like white noise.</p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggAcf</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis2-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggAcf</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis2-2.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>(<span class="dt">differences =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ggAcf</span>()</code></pre>
<p><img src="HW1_files/figure-html/vis2-3.png" width="672" /></p>
<p>The data ACF is decreasing linearly which indicates a non-stationary time series.</p>
<p>There difference is one lag above significance, we can use the Box-Ljung test to see if it is indeed significant. However, is stationary as the lags radiply decrease under the significance thershold. Two differences give two significant lags, but again rapidly decreases to zero.</p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">Box.test</span>(<span class="dt">lag=</span><span class="dv">10</span>, <span class="dt">type=</span><span class="st">&quot;Ljung-Box&quot;</span>)</code></pre>
<pre><code>## 
##  Box-Ljung test
## 
## data:  .
## X-squared = 12.958, df = 10, p-value = 0.226</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>(<span class="dt">differences =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">Box.test</span>(<span class="dt">lag=</span><span class="dv">10</span>, <span class="dt">type=</span><span class="st">&quot;Ljung-Box&quot;</span>)</code></pre>
<pre><code>## 
##  Box-Ljung test
## 
## data:  .
## X-squared = 40.778, df = 10, p-value = 1.235e-05</code></pre>
<p>The Box-Ljung test shows the first order difference is white noise to the 95% confidence level.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(urca)
wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ur.kpss</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</code></pre>
<pre><code>## 
## ####################### 
## # KPSS Unit Root Test # 
## ####################### 
## 
## Test is of type: mu with 3 lags. 
## 
## Value of test-statistic is: 0.6331 
## 
## Critical value for a significance level of: 
##                 10pct  5pct 2.5pct  1pct
## critical values 0.347 0.463  0.574 0.739</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ur.kpss</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</code></pre>
<pre><code>## 
## ####################### 
## # KPSS Unit Root Test # 
## ####################### 
## 
## Test is of type: mu with 3 lags. 
## 
## Value of test-statistic is: 0.4697 
## 
## Critical value for a significance level of: 
##                 10pct  5pct 2.5pct  1pct
## critical values 0.347 0.463  0.574 0.739</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>(<span class="dt">differences =</span> <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ur.kpss</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</code></pre>
<pre><code>## 
## ####################### 
## # KPSS Unit Root Test # 
## ####################### 
## 
## Test is of type: mu with 3 lags. 
## 
## Value of test-statistic is: 0.0458 
## 
## Critical value for a significance level of: 
##                 10pct  5pct 2.5pct  1pct
## critical values 0.347 0.463  0.574 0.739</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ndiffs</span>()</code></pre>
<pre><code>## [1] 2</code></pre>
<p>Both by the KPSS test and ndiff(), 2 differences seem to give the best result.</p>
<p>The KPSS test for 1 difference is marginally stationary as the test statstic is 0.0067 above the 95% confidence level.</p>
</div>
<div id="b-10" class="section level4">
<h4><span class="header-section-number">6.0.3.2</span> 8.7b</h4>
<p><img src="week5/8.7b.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</code></pre>
<pre><code>## [1] 3.392687</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">diff</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mean</span>()</code></pre>
<pre><code>## [1] 0.00296237</code></pre>
<p>There does not seem to be drift to the Random walk, so c = 0. There should not be a consant added.</p>
</div>
<div id="c-9" class="section level4">
<h4><span class="header-section-number">6.0.3.3</span> 8.7c</h4>
<p><img src="week5/8.7c.png" /></p>
<p><span class="math display">\[
(1 - \phi_1B)(1-B)^2y_t = c + (1 - \theta_1B)e_t
\]</span></p>
<p>However it appears that the constant is zero as is the moving average part so:</p>
<p><span class="math display">\[
(1 - \phi_1B)(1-B)^2y_t = (1 - \theta_1B)e_t
\]</span></p>
</div>
<div id="d-5" class="section level4">
<h4><span class="header-section-number">6.0.3.4</span> 8.7d</h4>
<p><img src="week5/8.7d.png" /></p>
<p>It seems like a 1,1,1 or 1,2,1 model may be the best, but we will test against some similar models to see how they perform.</p>
<pre class="sourceCode r"><code class="sourceCode r">orders &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">1</span>),<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>)), <span class="dt">nrow =</span> <span class="dv">10</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)
orders</code></pre>
<pre><code>##       [,1] [,2] [,3]
##  [1,]    1    0    0
##  [2,]    0    1    0
##  [3,]    0    0    1
##  [4,]    1    1    0
##  [5,]    1    0    1
##  [6,]    0    1    1
##  [7,]    1    1    1
##  [8,]    2    1    1
##  [9,]    1    2    1
## [10,]    1    1    2</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>(row <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(orders)){
  fit &lt;-<span class="st"> </span>wmurders <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">Arima</span>(<span class="dt">order =</span> orders[row,])
  <span class="kw">checkresiduals</span>(fit)
  <span class="kw">print</span>(fit<span class="op">$</span>aicc)
}</code></pre>
<p><img src="HW1_files/figure-html/models-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,0) with non-zero mean
## Q* = 12.887, df = 8, p-value = 0.1158
## 
## Model df: 2.   Total lags used: 10
## 
## [1] -6.095071</code></pre>
<p><img src="HW1_files/figure-html/models-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,0)
## Q* = 13.165, df = 10, p-value = 0.2146
## 
## Model df: 0.   Total lags used: 10
## 
## [1] -11.38057</code></pre>
<p><img src="HW1_files/figure-html/models-3.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,0,1) with non-zero mean
## Q* = 153.81, df = 8, p-value &lt; 2.2e-16
## 
## Model df: 2.   Total lags used: 10
## 
## [1] 81.0769</code></pre>
<p><img src="HW1_files/figure-html/models-4.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,0)
## Q* = 13.281, df = 9, p-value = 0.1503
## 
## Model df: 1.   Total lags used: 10
## 
## [1] -9.610749</code></pre>
<p><img src="HW1_files/figure-html/models-5.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,1) with non-zero mean
## Q* = 12.918, df = 7, p-value = 0.07414
## 
## Model df: 3.   Total lags used: 10
## 
## [1] -3.93281</code></pre>
<p><img src="HW1_files/figure-html/models-6.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,1)
## Q* = 13.122, df = 9, p-value = 0.1572
## 
## Model df: 1.   Total lags used: 10
## 
## [1] -9.46505</code></pre>
<p><img src="HW1_files/figure-html/models-7.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,1)
## Q* = 11.266, df = 8, p-value = 0.1871
## 
## Model df: 2.   Total lags used: 10
## 
## [1] -9.876999</code></pre>
<p><img src="HW1_files/figure-html/models-8.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(2,1,1)
## Q* = 9.4234, df = 7, p-value = 0.2237
## 
## Model df: 3.   Total lags used: 10
## 
## [1] -10.16966</code></pre>
<p><img src="HW1_files/figure-html/models-9.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,2,1)
## Q* = 12.419, df = 8, p-value = 0.1335
## 
## Model df: 2.   Total lags used: 10
## 
## [1] -6.389972</code></pre>
<p><img src="HW1_files/figure-html/models-10.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,2)
## Q* = 9.9439, df = 7, p-value = 0.1918
## 
## Model df: 3.   Total lags used: 10
## 
## [1] -10.62525</code></pre>
<p>It seems like an ARIMA(1,2,1) is best in terms of residual behavior and AICc. Some of the lower AICc values have worse residuals and ACF plots.</p>
</div>
<div id="e-4" class="section level4">
<h4><span class="header-section-number">6.0.3.5</span> 8.7e</h4>
<p><img src="week5/8.7e.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">three_ahead &lt;-<span class="st"> </span>fit <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">forecast</span>(<span class="dt">h=</span><span class="dv">3</span>)
three_ahead</code></pre>
<pre><code>##      Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2005       2.450027 2.184288 2.715766 2.043615 2.856439
## 2006       2.463104 2.098363 2.827846 1.905280 3.020928
## 2007       2.463646 1.957435 2.969857 1.689463 3.237828</code></pre>
<p><span class="math display">\[
(1 - \phi B)(1-B)^2y_t = (1 - \theta B)e_t\\
\phi_1 = 0.395 \\
\phi_2 = -0.65 \\
\phi_2 = 0.05 \\
\theta_1 = 1  \\
y_t = \phi_1y_{t-1} - \phi_2 y_{t-2} + \phi_3 y_{t-3} +\epsilon_t + \theta_1\epsilon_{t-1} \\
y_t = 0.395y_{t-1} + 0.65y_{t-2} + 0.05 y_{t-3} +\epsilon_t + \epsilon_{t-1}
\]</span></p>
<pre class="sourceCode r"><code class="sourceCode r">phi_<span class="dv">1</span> =<span class="st"> </span><span class="fl">0.395</span>
phi_<span class="dv">2</span> =<span class="st"> </span><span class="fl">0.65</span>
phi_<span class="dv">3</span> =<span class="st"> </span><span class="fl">0.005</span>
theta_<span class="dv">1</span> =<span class="st"> </span><span class="dv">1</span>
y_t_<span class="dv">1</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
y_t_<span class="dv">2</span> =<span class="st"> </span>wmurders[<span class="dv">2</span>]
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">3</span>]
e_t =<span class="st"> </span>fit<span class="op">$</span>residuals[<span class="dv">1</span>]
e_t_<span class="dv">1</span> =fit<span class="op">$</span>residuals[<span class="dv">2</span>]
y_<span class="dv">2005</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2005</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.448481</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">y_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2005</span>
y_t_<span class="dv">2</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">2</span>]
e_t =<span class="st"> </span>y_<span class="dv">2005</span> <span class="op">-</span><span class="st">  </span>wmurders[<span class="dv">1</span>] <span class="co">#error from naive model estimate</span>
e_t_<span class="dv">1</span> =<span class="st"> </span>fit<span class="op">$</span>residuals[<span class="dv">1</span>]
y_<span class="dv">2006</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2006</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.579583</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">y_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2006</span>
y_t_<span class="dv">2</span> =<span class="st"> </span>y_<span class="dv">2005</span>
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
e_t =<span class="st"> </span>y_<span class="dv">2006</span> <span class="op">-</span><span class="st">  </span>y_<span class="dv">2005</span> <span class="co">#error from naive model estimate</span>
e_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2005</span> <span class="op">-</span><span class="st">  </span>wmurders[<span class="dv">1</span>]
y_<span class="dv">2007</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2007</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.772763</code></pre>
<p>Our by-hand method of the (1,2,1) model gives a steeper upward trend than the included method. The challenge for matching the by-hand model to the R fucntion is balancing the parameters of <span class="math inline">\(\phi_{1,2,3}\)</span> and <span class="math inline">\(\theta_1\)</span>. This was done emptically and it became appearant that small changes to the paramters made big changes in the predictions as given below:</p>
<pre class="sourceCode r"><code class="sourceCode r">phi_<span class="dv">1</span> =<span class="st"> </span><span class="fl">0.5</span>
phi_<span class="dv">2</span> =<span class="st"> </span><span class="fl">0.495</span>
phi_<span class="dv">3</span> =<span class="st"> </span><span class="fl">0.005</span>
theta_<span class="dv">1</span> =<span class="st"> </span><span class="dv">1</span>
y_t_<span class="dv">1</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
y_t_<span class="dv">2</span> =<span class="st"> </span>wmurders[<span class="dv">2</span>]
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">3</span>]
e_t =<span class="st"> </span>fit<span class="op">$</span>residuals[<span class="dv">1</span>]
e_t_<span class="dv">1</span> =fit<span class="op">$</span>residuals[<span class="dv">2</span>]
y_<span class="dv">2005</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2005</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.337249</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">y_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2005</span>
y_t_<span class="dv">2</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">2</span>]
e_t =<span class="st"> </span>y_<span class="dv">2005</span> <span class="op">-</span><span class="st">  </span>wmurders[<span class="dv">1</span>] <span class="co">#error from naive model estimate</span>
e_t_<span class="dv">1</span> =<span class="st"> </span>fit<span class="op">$</span>residuals[<span class="dv">1</span>]
y_<span class="dv">2006</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2006</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.293265</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">y_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2006</span>
y_t_<span class="dv">2</span> =<span class="st"> </span>y_<span class="dv">2005</span>
y_t_<span class="dv">3</span> =<span class="st"> </span>wmurders[<span class="dv">1</span>]
e_t =<span class="st"> </span>y_<span class="dv">2006</span> <span class="op">-</span><span class="st">  </span>y_<span class="dv">2005</span> <span class="co">#error from naive model estimate</span>
e_t_<span class="dv">1</span> =<span class="st"> </span>y_<span class="dv">2005</span> <span class="op">-</span><span class="st">  </span>wmurders[<span class="dv">1</span>]
y_<span class="dv">2007</span> =<span class="st"> </span>phi_<span class="dv">1</span><span class="op">*</span>y_t_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">2</span><span class="op">*</span>y_t_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span>phi_<span class="dv">3</span><span class="op">*</span>y_t_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>e_t <span class="op">+</span>theta_<span class="dv">1</span><span class="op">*</span>e_t_<span class="dv">1</span>
y_<span class="dv">2007</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">print</span>()</code></pre>
<pre><code>## [1] 2.179567</code></pre>
<p>Here shift the weight from <span class="math inline">\(\phi_2\)</span> to <span class="math inline">\(\phi_1\)</span> by 0.105 and instead of getting an increasing trend we get a decreasing trend. The first example respresents our best attempt to constrain the <span class="math inline">\(\phi\)</span> parameters empirically.</p>
</div>
<div id="f-4" class="section level4">
<h4><span class="header-section-number">6.0.3.6</span> 8.7f</h4>
<p><img src="week5/8.7f.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r">fit <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">forecast</span>(<span class="dt">h=</span><span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">autoplot</span>()</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-109-1.png" width="672" /></p>
<p>Does auto.arima() give the same model you have chosen? If not, which model do you think is better?</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">auto.arima</span>(wmurders)</code></pre>
<pre><code>## Series: wmurders 
## ARIMA(1,2,1) 
## 
## Coefficients:
##           ar1      ma1
##       -0.2434  -0.8261
## s.e.   0.1553   0.1143
## 
## sigma^2 estimated as 0.04632:  log likelihood=6.44
## AIC=-6.88   AICc=-6.39   BIC=-0.97</code></pre>
<p>It give the same answer.</p>
</div>
<div id="g-2" class="section level4">
<h4><span class="header-section-number">6.0.3.7</span> 8.7g</h4>
<p><img src="week5/8.7g.png" /></p>
</div>
</div>
<div id="section-15" class="section level3">
<h3><span class="header-section-number">6.0.4</span> 8.12</h3>
<p><img src="week5/8.12.png" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(mcopper)
<span class="kw">autoplot</span>(mcopper)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<div id="a-11" class="section level4">
<h4><span class="header-section-number">6.0.4.1</span> 8.12a</h4>
<p><img src="week5/8.12a.png" /></p>
<p>Answer: given the huge spike in 2005-2010 in copper prices, a Box-Cox transformation to help with the increased variance would be useful. A Box-Cox test finds a lambda of 0.191 to be optimal.</p>
<pre class="sourceCode r"><code class="sourceCode r">lambda &lt;-<span class="kw">BoxCox.lambda</span>(mcopper)
mcopper_adj &lt;-<span class="st"> </span><span class="kw">BoxCox</span>(mcopper,lambda)
<span class="kw">autoplot</span>(mcopper_adj)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-111-1.png" width="672" /></p>
</div>
<div id="b-11" class="section level4">
<h4><span class="header-section-number">6.0.4.2</span> 8.12b</h4>
<p><img src="week5/8.12b.png" /></p>
<p>Answer: auto.arima() finds an ARIMA(0,1,1) model, meaning that we have a 0 autoregressive part, with a single first degree difference, and 1 for the moving average part.</p>
<pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">auto.arima</span>(mcopper_adj)
<span class="kw">summary</span>(model)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(0,1,1) 
## 
## Coefficients:
##          ma1
##       0.3720
## s.e.  0.0388
## 
## sigma^2 estimated as 0.04997:  log likelihood=45.05
## AIC=-86.1   AICc=-86.08   BIC=-77.43
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01254827 0.2231365 0.1592271 0.08049384 1.140225 0.1997301
##                      ACF1
## Training set -0.004184621</code></pre>
</div>
<div id="c-10" class="section level4">
<h4><span class="header-section-number">6.0.4.3</span> 8.12c</h4>
<p><img src="week5/8.12c.png" /></p>
<p>Answer: I tried six other options with different orders. All were either equal or less in log likelihood or had higher AIC and AICc. They were also more complicated by adding, for example, an autoregressive part when the above model doesn’t have one.</p>
<pre class="sourceCode r"><code class="sourceCode r">option1 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>))
<span class="kw">summary</span>(option1)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(1,0,1) with non-zero mean 
## 
## Coefficients:
##          ar1     ma1     mean
##       0.9955  0.3740  14.1730
## s.e.  0.0044  0.0388   2.1536
## 
## sigma^2 estimated as 0.05009:  log likelihood=42.77
## AIC=-77.55   AICc=-77.48   BIC=-60.21
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01102121 0.2232071 0.1600608 0.05878252 1.148836 0.2007759
##                      ACF1
## Training set -0.003909071</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">option2 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>))
<span class="kw">summary</span>(option2)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(1,1,0) 
## 
## Coefficients:
##          ar1
##       0.3231
## s.e.  0.0399
## 
## sigma^2 estimated as 0.05091:  log likelihood=39.83
## AIC=-75.66   AICc=-75.64   BIC=-66.99
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01154793 0.2252223 0.1601516 0.07483773 1.147554 0.2008897
##                    ACF1
## Training set 0.03831971</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">option3 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))
<span class="kw">summary</span>(option3)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(0,1,0) 
## 
## sigma^2 estimated as 0.05674:  log likelihood=8.85
## AIC=-15.7   AICc=-15.69   BIC=-11.37
## 
## Training set error measures:
##                      ME      RMSE       MAE       MPE     MAPE      MASE
## Training set 0.01733237 0.2379863 0.1716493 0.1074569 1.227148 0.2153122
##                   ACF1
## Training set 0.3187708</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">option4 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>))
<span class="kw">summary</span>(option4)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(1,0,0) with non-zero mean 
## 
## Coefficients:
##          ar1     mean
##       0.9980  13.9151
## s.e.  0.0025   3.0608
## 
## sigma^2 estimated as 0.05692:  log likelihood=6.21
## AIC=-6.41   AICc=-6.37   BIC=6.59
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01677141 0.2381561 0.1721394 0.09649416 1.232327 0.2159269
##                   ACF1
## Training set 0.3189333</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">option5 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">1</span>))
<span class="kw">summary</span>(option5)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(0,2,1) 
## 
## Coefficients:
##           ma1
##       -1.0000
## s.e.   0.0066
## 
## sigma^2 estimated as 0.05664:  log likelihood=6.66
## AIC=-9.32   AICc=-9.3   BIC=-0.66
## 
## Training set error measures:
##                       ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.004015354 0.2373549 0.1711164 0.01596248 1.225196 0.2146437
##                   ACF1
## Training set 0.3187439</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">option6 &lt;-<span class="kw">Arima</span>(mcopper_adj, <span class="dt">order=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))
<span class="kw">summary</span>(option6)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(1,1,1) 
## 
## Coefficients:
##           ar1     ma1
##       -0.0092  0.3797
## s.e.   0.1053  0.0961
## 
## sigma^2 estimated as 0.05006:  log likelihood=45.05
## AIC=-84.1   AICc=-84.06   BIC=-71.1
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE    MAPE     MASE
## Training set 0.01259577 0.2231351 0.1592422 0.08076154 1.14026 0.199749
##                      ACF1
## Training set -0.002728724</code></pre>
</div>
<div id="d-6" class="section level4">
<h4><span class="header-section-number">6.0.4.4</span> 8.12d</h4>
<p><img src="week5/8.12d.png" /></p>
<p>Answer: for the reasons given above, the original model is the best. We can confirm this by also forcing auto.arima() to check more of the available options. It still returns an ARIMA(0,1,1) model.</p>
<p>The residuals look good. A Ljung-Box test returns a p-value of 0.4659 which is not significant. The residuals are normally distributed, are not autocorrelated, and have roughly stable variance over time. So the model appears to pass the test.</p>
<pre class="sourceCode r"><code class="sourceCode r">model2 &lt;-<span class="st"> </span><span class="kw">auto.arima</span>(mcopper_adj,  <span class="dt">stepwise=</span><span class="ot">FALSE</span>, <span class="dt">approximation=</span><span class="ot">FALSE</span>)
<span class="kw">summary</span>(model2)</code></pre>
<pre><code>## Series: mcopper_adj 
## ARIMA(0,1,1) 
## 
## Coefficients:
##          ma1
##       0.3720
## s.e.  0.0388
## 
## sigma^2 estimated as 0.04997:  log likelihood=45.05
## AIC=-86.1   AICc=-86.08   BIC=-77.43
## 
## Training set error measures:
##                      ME      RMSE       MAE        MPE     MAPE      MASE
## Training set 0.01254827 0.2231365 0.1592271 0.08049384 1.140225 0.1997301
##                      ACF1
## Training set -0.004184621</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="co">#residuals</span>
<span class="kw">checkresiduals</span>(model)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-114-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,1,1)
## Q* = 22.913, df = 23, p-value = 0.4659
## 
## Model df: 1.   Total lags used: 24</code></pre>
</div>
<div id="e-5" class="section level4">
<h4><span class="header-section-number">6.0.4.5</span> 8.12e</h4>
<p><img src="week5/8.12e.png" /></p>
<p>Answer: a forecast of the fitted model looks reasonable. The prediction interval seems to be wide enough to capture what, based on looking at the historical data, are the likely values to come.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(<span class="kw">forecast</span>(model))</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
</div>
<div id="f-5" class="section level4">
<h4><span class="header-section-number">6.0.4.6</span> 8.12f</h4>
<p><img src="week5/8.12f.png" /></p>
<p>Answer: The ARIMA model appears to be a better model. The prediction intervals are much smaller (the ETS intervals provide almost no real help in what the value could be). Comparing summary statistics, the ARIMA model has AIC of -86.1, AICc 0f -86.08, and BIC of -77.43. Other measures are RMSE (0.223), MAE (0.159), MAPE (1.14), and MASE (0.199).</p>
<p>In contrast, the ETS model has very high AIC (1919), AICc (1919), and BIC (1945). Other measures are similar or higher: RMSE(0.233), MAE (0.166), MAPE(1.19), and MASE(0.208).</p>
<p>Also, the ETS model does not account for some autocorrelation, as shown by the ACF plot below and as given by the Ljung-Box test p-value of basically 0 (meaning that the results are significant and we can conclude that there is autocorrelation).</p>
<p>So the ETS model in this instance does not do very well at all in comparison to the ARIMA model, which is much more useful in its predictions and much more accurate with respect to model measures.</p>
<pre class="sourceCode r"><code class="sourceCode r">model_ets&lt;-<span class="kw">ets</span>(mcopper_adj)
<span class="kw">autoplot</span>(<span class="kw">forecast</span>(model_ets))</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-116-1.png" width="672" /></p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(model_ets)</code></pre>
<pre><code>## ETS(M,Ad,N) 
## 
## Call:
##  ets(y = mcopper_adj) 
## 
##   Smoothing parameters:
##     alpha = 0.9971 
##     beta  = 0.26 
##     phi   = 0.8 
## 
##   Initial states:
##     l = 9.9204 
##     b = -0.2684 
## 
##   sigma:  0.0168
## 
##      AIC     AICc      BIC 
## 1919.482 1919.633 1945.492 
## 
## Training set error measures:
##                       ME      RMSE       MAE        MPE    MAPE      MASE
## Training set 0.008892997 0.2330528 0.1662713 0.06395868 1.19264 0.2085661
##                   ACF1
## Training set 0.1508258</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">checkresiduals</span>(model_ets)</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-116-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ETS(M,Ad,N)
## Q* = 80.996, df = 19, p-value = 1.252e-09
## 
## Model df: 5.   Total lags used: 24</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hw4.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/05-Week5-HW.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["HW1.pdf", "HW1.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
